name: publish-curation
on:
  push:
    branches:
      - curation
  workflow_dispatch:

env:
  MAP_SERVER: https://mapcore-demo.org/curation/flatmap
  REMOTE_MAKER: https://github.com/AnatomicMaps/remotemaker/releases/download/v0.1.7/remotemaker-0.1.7-py3-none-any.whl

jobs:
  generate-map:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install remotemaker
        run: |
          python -m pip install $REMOTE_MAKER
      - name: run remotemaker
        run: |
          python -m remotemaker \
                 --server $MAP_SERVER \
                 --token ${{ secrets.CURATION_SERVER_TOKEN }} \
                 --source ${{ github.server_url }}/${{ github.repository }} \
                 --manifest manifest.json \
                 --commit curation
